version: '3.8'

services:
  web:
    build: .
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./app
    ports:
      - 5000:5000
#    env_file:
#      .
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=testdb
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  postgres_data:
